from __future__ import annotations

class Square:
    def __init__(self, x, y) -> None: ...

class Board:
    def __init__(self) -> None: ...
    async def as_string(self) -> str: ...
    async def assign_square(self, x, y) -> str | None: ...
    async def check_connects(self) -> str | None: ...
