from __future__ import annotations
from itertools import chain

class SQ:
    def __init__(self) -> None: ...
    def __str__(self) -> str: ...

class C4Board:
    """a connect-four board"""

    def __init__(self) -> None: ...
    async def as_string(self) -> tuple[str, str]:
        """string representation of current board

        returns a tuple of two strings being the original string
        split in half, emojis are replaced with :name: aswell

        """
        ...
    async def drop_square(self, r) -> None | str: ...
    async def check_four(self) -> None | str: ...
    @staticmethod
    async def strs_in_list(rw: list) -> list[str]: ...
